<?php
session_start();
// Corrected path: move up 2 steps (process/ -> php/ -> back-end/) to reach db.php
include "../../db.php";

// 1. Force safety checkpoint redirect if no logged-in user session exists
if (!isset($_SESSION['user_id'])) {
    // Corrected path: move up 4 steps (process/ -> php/ -> back-end/ -> Paluwagan/ -> Group-ECHO/) to reach root index.php
    header("Location: ../../../../index.php");
    exit();
}

// 2. Form submission intercept
if ($_SERVER["REQUEST_METHOD"] == "POST") {
    $owner_id = $_SESSION['user_id'];
    
    // Sanitize inbound text inputs
    $group_name = mysqli_real_escape_string($conn, trim($_POST['group_name']));
    $contribution = isset($_POST['contribution']) ? floatval($_POST['contribution']) : 0.00;
    $frequency = isset($_POST['frequency']) ? mysqli_real_escape_string($conn, $_POST['frequency']) : 'monthly';
    
    // ─── GENERATE THE MISSING 6-CHARACTER ALPHANUMERIC INVITE CODE ───
    // This produces codes matching your screenshot requirements (e.g., 1KUOD5)
    $invite_code = strtoupper(substr(md5(uniqid(mt_rand(), true)), 0, 6));

    // 3. Match columns directly with your TrustFund schema setup
    $insert_group = "INSERT INTO groups (group_name, owner_id, contribution, frequency, invite_code, status) 
                     VALUES ('$group_name', '$owner_id', '$contribution', '$frequency', '$invite_code', 'active')";

    if (mysqli_query($conn, $insert_group)) {
        // Capture the primary numeric group identification sequence generated by MySQL auto-increment
        $new_group_id = mysqli_insert_id($conn);

        // 4. Auto-bind the creator user account record array into their own newly created group circle mapping
        $join_creator = "INSERT INTO group_members (user_id, group_id, status) 
                         VALUES ('$owner_id', '$new_group_id', 'active')";
        mysqli_query($conn, $join_creator);

        // Success redirect back to workspace dashboard array viewport rendering target
        // Corrected path: move up 1 step out of process/ to reach my_groups.php in php/
        header("Location: ../my_groups.php?success=" . urlencode("Group created successfully!"));
        exit();
    } else {
        // Fallback error flag handling if database structure tracks error limits
        // Corrected path: move up 1 step out of process/ to reach my_groups.php in php/
        header("Location: ../my_groups.php?error=" . urlencode("Failed to write structural records database context row: " . mysqli_error($conn)));
        exit();
    }
}
?>