-- =====================================================
-- Group-ECHO / Paluwagan - MINIMAL DEMO SEED (SQL only)
-- =====================================================
-- Use this ONLY if you cannot run the PHP seeder (seed_demo_data.php).
-- This is a tiny sample ( ~25 users + 4 groups + basic activity ).
-- For the full "100 people, 3 years, thousands of tx" experience, run:
--   http://localhost/Group-ECHO/sql/seed_demo_data.php?reset=1
--
-- IMPORTANT: Run the main schema first: sql/trustfund_oltp.sql
-- Then run this (or the PHP seeder).
-- All demo logins use the password hash: $2y$10$GKfh18Ysah5fH9O7w2o0puPVdUo3E7hREQAR52DgPuPpLP8tD891u
-- =====================================================

SET NAMES utf8mb4;
USE trustfund_db;

-- Fixed demo bcrypt password hash (as requested)
-- If login fails with this, run the UPDATE at the bottom or use the PHP seeder instead.
SET @DEMO_HASH = '$2y$10$GKfh18Ysah5fH9O7w2o0puPVdUo3E7hREQAR52DgPuPpLP8tD891u'; -- fixed demo password hash

-- 3 Admins (early users)
INSERT INTO users (username, first_name, last_name, email, phone, occupation, address, password_hash, role, created_at, status) VALUES
('admin.juan', 'Juan', 'Dela Cruz', 'juan.delacruz@demo.ph', '+63 917 123 4567', 'Teacher', 'Quezon City, Metro Manila', @DEMO_HASH, 'admin', '2023-04-12 09:15:00', 'activated'),
('maria.admin', 'Maria', 'Santos', 'maria.santos@demo.ph', '+63 918 234 5678', 'Nurse', 'Makati City', @DEMO_HASH, 'admin', '2023-05-03 14:22:00', 'activated'),
('carlos.sys', 'Carlos', 'Reyes', 'carlos.reyes@demo.ph', '+63 919 345 6789', 'Software Engineer', 'Cebu City', @DEMO_HASH, 'admin', '2023-05-28 11:05:00', 'activated');

-- Sample regular members (add more manually or use the PHP seeder for 100+)
INSERT INTO users (username, first_name, last_name, email, phone, occupation, address, password_hash, role, created_at, status) VALUES
('ana.reyes', 'Ana', 'Reyes', 'ana.reyes@gmail.com', '+63 917 111 2222', 'Call Center Agent', 'Pasig City', @DEMO_HASH, 'member', '2023-06-10 08:30:00', 'activated'),
('pedro.cruz', 'Pedro', 'Cruz', 'pedro.cruz@yahoo.com', '+63 918 333 4444', 'Grab Driver', 'Manila', @DEMO_HASH, 'member', '2023-07-22 19:45:00', 'activated'),
('sofia.mendoza', 'Sofia', 'Mendoza', 'sofia.mendoza@demo.ph', '+63 919 555 6666', 'OFW - Healthcare', 'Davao City', @DEMO_HASH, 'member', '2023-08-05 10:10:00', 'activated'),
('miguel.tan', 'Miguel', 'Tan', 'miguel.tan@gmail.com', '+63 917 777 8888', 'Small Business Owner', 'Cebu City', @DEMO_HASH, 'member', '2023-09-14 16:00:00', 'activated'),
('luna.garcia', 'Luna', 'Garcia', 'luna.garcia@outlook.com', '+63 918 999 0000', 'Teacher', 'Baguio City', @DEMO_HASH, 'member', '2024-01-20 09:00:00', 'activated');

-- A few verifications for the admins + early members
INSERT INTO user_verifications (user_id, document, verified_at, status) VALUES
(1, 'verify_1_1780925544.png', '2023-04-16 10:00:00', 'approved'),
(2, 'verify_2_1780925663.jpg', '2023-05-07 15:30:00', 'approved'),
(3, 'verify_3_demo.png', '2023-06-01 12:00:00', 'approved');

-- 4 Public groups (small historical activity)
INSERT INTO groups (group_name, description, privacy, contribution_amount, max_members, frequency, cycle_length, current_cycle, invite_code, is_active, status, created_by, created_at) VALUES
('Sunrise Savings Circle', 'Long-running community paluwagan. 3 years of successful rotations.', 'public', 1000.00, 6, 'monthly', 6, 6, NULL, 1, 'completed', 1, '2023-05-15 00:00:00'),
('Barkada Paluwagan 2024', 'Friends and coworkers saving together. Still active.', 'public', 1500.00, 8, 'monthly', 8, 5, NULL, 1, 'active', 2, '2024-02-10 00:00:00'),
('OFW Dream Fund 2025', 'OFWs and families building capital back home.', 'public', 2000.00, 7, 'monthly', 7, 3, NULL, 1, 'active', 1, '2025-03-01 00:00:00'),
('Market Vendors Trust', 'Public group for small vendors in the public market.', 'public', 500.00, 10, 'biweekly', 10, 10, NULL, 1, 'completed', 3, '2023-11-20 00:00:00');

-- NOTE: Full cycles, members, contributions, payouts, and transactions are best generated by the PHP seeder
-- (it creates proper historical dates, respects "position == cycle_number gets the payout", wallet movements, group_history, etc.)

-- After running either seeder, update one user to admin if you need more, and run the OLAP ETL.

-- If the hash above doesn't let you log in with the expected password, run:
-- UPDATE users SET password_hash = '$2y$10$GKfh18Ysah5fH9O7w2o0puPVdUo3E7hREQAR52DgPuPpLP8tD891u' WHERE 1=1;

SELECT 'Minimal seed inserted. For rich 3-year demo with 100+ users and thousands of records, use seed_demo_data.php instead.' AS note;
